### ISSUE TITLE
Sum up multiple lanes to one

### ISSUE THREAD

**Issue by derBaSche** [nicoespeon/trello-kanban-analysis-tool#48]
Hi,

thanks for this awesome tool. It seems to help me and my team a lot.

One feature would be actually pretty great. We use several lanes for done-cards (one per sprint). It would be awesome if you could somehow select several lanes and have them collapsed and sum up to only one area on the CFD. One step further, you could also go for a separate board, where all done cards are moved to.

What do you think?

Cheers,
BaSche

**Comment by nicoespeon** [comment]
Hi @derBaSche, thanks for your suggestion.

Indeed, I can see the use case of grouping several columns under a unique label (eg: "Done").
I need to figure out how to make it simple enough so the UI still clear to use.

I guess we could start being very specific: enabling user to select multiple "Work ends" columns that will be considered as a unique "Done" column instead of one (currently).

Would that seem clear for you? Do you visualize something in terms of interface?

**Comment by nicoespeon** [comment]
Hi @derBaSche,

I'm closing this issue because it's getting old and there was no more feedback on it.
Feel free to poke me back on this one if needed.

Thanks!
